/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}  //   用于无法到处模块的解决方式
// 声明为模块
declare module 'vue'{
    export interface GlobalComponents {
        Wave: typeof import('../components/Wave/index.vue')['default']
        SvgIcon: typeof import('../components/SvgIcon/index.vue')['default']
    }
}


